// Question decks for The Whole Truth.
// {P} is replaced with the subject player's name.

export const PARTY = [
  'The real reason {P} was late last time',
  'What {P} would do first after winning the lottery',
  "The title of {P}'s autobiography",
  'What {P} says to the mirror before leaving the house',
  "{P}'s secret talent that nobody asked about",
  "The weirdest thing in {P}'s search history this week",
  'The one item {P} would bring to a deserted island',
  "{P}'s villain origin story begins with...",
  'The reality show {P} would definitely win',
  "What {P}'s pet would say about them if it could talk",
  'What {P} is really thinking about during long meetings',
  "{P}'s superpower, if superpowers were useless",
  'The last thing {P} googled at 3am',
  'What {P} would name their yacht',
  "{P}'s catchphrase, if they had one",
  'The job {P} would be hilariously bad at',
  "What's actually in {P}'s junk drawer",
  'The movie role {P} was born to play',
  "{P}'s most irrational fear",
  'What {P} does when nobody is watching',
  'The world record {P} could actually break',
  "{P}'s spirit animal, and why",
  "The first rule of {P}'s secret club",
  'What {P} would say to their 13-year-old self',
  "{P}'s go-to karaoke song that clears the room",
  'The warning label {P} should come with',
  "{P}'s doomsday plan, in five words",
  'The conspiracy theory {P} secretly believes',
  'What {P} would do as president for one day',
  "{P}'s biggest kitchen disaster",
  'The app {P} checks way too often',
  "What {P}'s GPS voice wishes it could say to them",
  "{P}'s hidden browser bookmark folder is named...",
  "The sport {P} thinks they'd be great at (they would not)",
  'What {P} was famous for in a past life',
  "{P}'s tombstone will read...",
  'The one thing {P} would grab in a fire (after people and pets)',
  'What {P} practices in the shower',
  "{P}'s WiFi password is probably...",
  'The award {P} deserves but will never get',
  'What {P} would do with an invisibility cloak for one day',
  "{P}'s brain at 2am keeps them awake with...",
  'The store {P} could spend an entire paycheck in',
  'What aliens would report back after abducting {P}',
  "{P}'s cooking show would be called...",
  'The excuse {P} uses way too often',
  "What {P}'s childhood imaginary friend was like",
  "{P}'s theme song when they walk into a room",
  'The thing {P} pretends to understand but absolutely does not',
  'What {P} would hoard in an apocalypse',
  "{P}'s guilty pleasure TV show",
  'The text {P} would hate to send to the wrong person',
  "What {P}'s socks say about their personality",
  'The dream job {P} had at age five',
  'The one chore {P} would pay anything to never do again',
  "{P}'s honest opinion about pineapple on pizza",
  "{P}'s secret snack stash contains...",
  'The talent show act {P} would perform with zero practice',
  'The smell that instantly transports {P} back to childhood',
  "The nickname {P}'s family uses that they hate",
]

export const SPICY = [
  "The most scandalous thing on {P}'s bucket list",
  "{P}'s dating profile, if it were brutally honest",
  "What {P} was really doing when they said they 'went to bed early'",
  'The text {P} regrets sending after midnight',
  "{P}'s celebrity hall pass",
  "What {P}'s incognito tab is hiding right now",
  "{P}'s worst date ever involved...",
  'The pickup line {P} has definitely used',
  "What {P} wears when absolutely nobody is coming over",
  "{P}'s guilty late-night habit",
  "The rumor about {P} that's probably true",
  'What {P} would do in Vegas that stays in Vegas',
  "{P}'s flirting technique, in three words",
  "The most embarrassing thing in {P}'s nightstand",
  "What {P}'s ex would say about them in one sentence",
  "{P}'s safe word is probably...",
  'What {P} looks for first in a person (be honest)',
  "{P}'s most questionable crush ever",
  'The lie {P} tells on every first date',
  "What {P} did at the last party that we don't talk about",
  "{P}'s love language, according to their exes",
  'The DM {P} would die if anyone saw',
  'What {P} thinks makes them irresistible',
  "The number {P} claims, versus {P}'s real number",
  "The song on {P}'s 'special occasion' playlist",
  'What {P} practices before a hot date',
  "{P}'s type, based on their questionable history",
  'The thing {P} finds weirdly attractive',
  "What {P}'s search history looked like on Valentine's Day",
  "{P}'s most dramatic breakup story, in five words",
  'The tattoo {P} would get after three margaritas',
  'What {P} would do if their crush walked in right now',
  "{P}'s secret weapon for seduction",
  'The reason {P} once got a drink thrown at them',
  'The outfit {P} owns that should require a permit',
  "{P}'s hall-of-fame walk of shame involved...",
  'The app {P} swears they deleted (they did not)',
  'What {P} whispers in their sleep',
  "{P}'s idea of a perfect naughty weekend",
  'The body part {P} is secretly most proud of',
  'What {P} would do for a free drink',
  "{P}'s most cringeworthy flirting fail",
  'The costume {P} would wear to a very adult Halloween party',
  "What {P}'s group chat says about their love life",
  "{P}'s toxic trait in relationships",
  "The one-star review {P}'s ex would leave",
  'What {P} thinks counts as romance',
  "{P}'s emergency contact for bad decisions",
  'The dance move {P} busts out after two drinks',
  'What {P} would name their steamy romance novel',
  "{P}'s red flag that everyone politely ignores",
  'The wildest thing {P} has done to get someone’s attention',
  "Where {P}'s hands go during a scary movie",
  "{P}'s brutally honest turn-on",
  'The reason {P} is banned from the neighbor’s hot tub',
  'What {P} would confess after truth serum and tequila',
  "{P}'s 'it's complicated' story, in one sentence",
  'The thirst trap caption {P} has drafted but never posted',
  "The first thing {P} checks out on a person (they think it's subtle)",
  'The fantasy {P} would never admit to at dinner with the in-laws',
]

export function buildDeck(deckId) {
  if (deckId === 'party') return [...PARTY]
  if (deckId === 'spicy') return [...SPICY]
  return [...PARTY, ...SPICY]
}
