// Question decks for The Whole Truth.
// {P} is replaced with the subject player's first name.
// {they} {them} {their} {theirs} {themselves} resolve to he/she pronouns
// based on the subject's chosen sex (see questionText in main.jsx).
// Verbs after {they} use the third-person singular form (he hates / she hates).

export const PARTY = [
  'The real reason {P} was late last time',
  'What {P} would do first after winning the lottery',
  "The title of {P}'s autobiography",
  'What {P} says to the mirror before leaving the house',
  "{P}'s secret talent that nobody asked about",
  "The weirdest thing in {P}'s search history this week",
  'The one item {P} would bring to a deserted island',
  "{P}'s villain origin story begins with...",
  'The reality show {P} would definitely win',
  "What {P}'s pet would say about {them} if it could talk",
  'What {P} is really thinking about during long meetings',
  "{P}'s superpower, if superpowers were useless",
  'The last thing {P} googled at 3am',
  'What {P} would name {their} yacht',
  "{P}'s catchphrase, if {they} had one",
  'The job {P} would be hilariously bad at',
  "What's actually in {P}'s junk drawer",
  'The movie role {P} was born to play',
  "{P}'s most irrational fear",
  'What {P} does when nobody is watching',
  'The world record {P} could actually break',
  "{P}'s spirit animal, and why",
  "The first rule of {P}'s secret club",
  'What {P} would say to {their} 13-year-old self',
  "{P}'s go-to karaoke song that clears the room",
  'The warning label {P} should come with',
  "{P}'s doomsday plan, in five words",
  'The conspiracy theory {P} secretly believes',
  'What {P} would do as president for one day',
  "{P}'s biggest kitchen disaster",
  'The app {P} checks way too often',
  "What {P}'s GPS voice wishes it could say to {them}",
  "{P}'s hidden browser bookmark folder is named...",
  "The sport {P} thinks {they}'d be great at ({they} would not)",
  'What {P} was famous for in a past life',
  "{P}'s tombstone will read...",
  'The one thing {P} would grab in a fire (after people and pets)',
  'What {P} practices in the shower',
  "{P}'s WiFi password is probably...",
  'The award {P} deserves but will never get',
  'What {P} would do with an invisibility cloak for one day',
  "{P}'s brain at 2am keeps {them} awake with...",
  'The store {P} could spend an entire paycheck in',
  'What aliens would report back after abducting {P}',
  "{P}'s cooking show would be called...",
  'The excuse {P} uses way too often',
  "What {P}'s childhood imaginary friend was like",
  "{P}'s theme song when {they} walks into a room",
  'The thing {P} pretends to understand but absolutely does not',
  'What {P} would hoard in an apocalypse',
  "{P}'s guilty pleasure TV show",
  'The text {P} would hate to send to the wrong person',
  "What {P}'s socks say about {their} personality",
  'The dream job {P} had at age five',
  'The one chore {P} would pay anything to never do again',
  "{P}'s honest opinion about pineapple on pizza",
  "{P}'s secret snack stash contains...",
  'The talent show act {P} would perform with zero practice',
  'The smell that instantly transports {P} back to childhood',
  "The nickname {P}'s family uses that {they} hates",
  'The world championship {P} would win if napping counted',
  "{P}'s autobiography chapter titled 'Regrets' is mostly about...",
  'What {P} would do with one million dollars and 24 hours',
  "The smell {P} secretly loves but won't admit",
  'The five-year-old logic {P} still lives by',
  "What {P}'s browser tabs look like right now",
  'The infomercial product {P} would absolutely buy at 2am',
  "{P}'s signature dance move is called...",
  'The food {P} would eat every day if calories weren’t real',
  "What {P}'s last voicemail rambled about",
  'The animal that would win a staring contest against {P}',
  "{P}'s secret retirement plan involves...",
  'What {P} thinks the inside of a computer looks like',
  'The word {P} has been spelling wrong for years',
  "{P}'s zombie apocalypse job would be...",
  'The board game that makes {P} flip the table',
  'What {P} mutters in traffic',
  'The most {P} thing {P} has ever done',
  "{P}'s imaginary restaurant would only serve...",
  'The talent {P} claims on résumés but cannot do',
  "What {P}'s houseplants gossip about after {they} leaves the room",
  "The name of {P}'s 6am alarm",
  "{P}'s go-to party fact (that is completely wrong)",
  'The cartoon character {P} secretly relates to',
  'What {P} does alone in an elevator',
  'The item {P} has returned to a store with zero shame',
  "{P}'s ghost would haunt people by...",
  'The school subject {P} would fail if forced to retake it today',
  'The question {P} has asked Google more than once this week',
  'The Olympic sport {P} invented in {their} backyard',
  "{P}'s superhero name, based on {their} actual skills",
  'The chore {P} pretends not to see',
  'What {P} would smuggle into a movie theater',
  'The song {P} knows every word to but denies it',
  "{P}'s fortune cookie would read...",
  'The kitchen appliance {P} has definitely broken',
  'The contact name {P} uses for {their} least favorite person',
  "{P}'s hidden talent that only appears after midnight",
  'The parade float {P} deserves',
  'What {P} thinks is in Area 51',
  'The emoji {P} uses way too much, and what it really means',
  "{P}'s doorbell camera has captured {them} doing...",
  'The self-checkout crime {P} has committed',
  'The one name {P} would give a boat, a band, and a baby',
  "{P}'s Roomba would file a complaint about...",
  'The holiday {P} would invent',
  'What {P} practices saying before phone calls',
  'The free sample {P} has gone back for three times',
  "{P}'s weather forecast would just say...",
  'The museum exhibit about {P} would display...',
  'The group project role {P} always takes',
  "{P}'s brain screensaver is...",
  'The wrong lyric {P} has been singing for years',
  "What {P} would do if {they} won an award {they} didn't deserve",
  'The line {P} would happily wait three hours in',
  "{P}'s personal theme park ride would be called...",
  'The text that means {P} is about to make the group chat explode',
  'What {P} looks like trying to parallel park',
  'The last thing {P} applauded alone at home',
  "The conspiracy board in {P}'s garage connects string between...",
]

export const SPICY = [
  "The most scandalous thing on {P}'s bucket list",
  "{P}'s dating profile, if it were brutally honest",
  "What {P} was really doing when {they} said {they} 'went to bed early'",
  'The text {P} regrets sending after midnight',
  "{P}'s celebrity hall pass",
  "What {P}'s incognito tab is hiding right now",
  "{P}'s worst date ever involved...",
  'The pickup line {P} has definitely used',
  "What {P} wears when absolutely nobody is coming over",
  "{P}'s guilty late-night habit",
  "The rumor about {P} that's probably true",
  'What {P} would do in Vegas that stays in Vegas',
  "{P}'s flirting technique, in three words",
  "The most embarrassing thing in {P}'s nightstand",
  "What {P}'s ex would say about {them} in one sentence",
  "{P}'s safe word is probably...",
  'What {P} looks for first in a person (be honest)',
  "{P}'s most questionable crush ever",
  'The lie {P} tells on every first date',
  "What {P} did at the last party that we don't talk about",
  "{P}'s love language, according to {their} exes",
  'The DM {P} would die if anyone saw',
  'What {P} thinks makes {them} irresistible',
  "The number {P} claims, versus {P}'s real number",
  "The song on {P}'s 'special occasion' playlist",
  'What {P} practices before a hot date',
  "{P}'s type, based on {their} questionable history",
  'The thing {P} finds weirdly attractive',
  "What {P}'s search history looked like on Valentine's Day",
  "{P}'s most dramatic breakup story, in five words",
  'The tattoo {P} would get after three margaritas',
  'What {P} would do if {their} crush walked in right now',
  "{P}'s secret weapon for seduction",
  'The reason {P} once got a drink thrown at {them}',
  'The outfit {P} owns that should require a permit',
  "{P}'s hall-of-fame walk of shame involved...",
  'The app {P} swears {they} deleted ({they} did not)',
  'What {P} whispers in {their} sleep',
  "{P}'s idea of a perfect naughty weekend",
  'The body part {P} is secretly most proud of',
  'What {P} would do for a free drink',
  "{P}'s most cringeworthy flirting fail",
  'The costume {P} would wear to a very adult Halloween party',
  "What {P}'s group chat says about {their} love life",
  "{P}'s toxic trait in relationships",
  "The one-star review {P}'s ex would leave",
  'What {P} thinks counts as romance',
  "{P}'s emergency contact for bad decisions",
  'The dance move {P} busts out after two drinks',
  'What {P} would name {their} steamy romance novel',
  "{P}'s red flag that everyone politely ignores",
  'The wildest thing {P} has done to get someone’s attention',
  "Where {P}'s hands go during a scary movie",
  "{P}'s brutally honest turn-on",
  'The reason {P} is banned from the neighbor’s hot tub',
  'What {P} would confess after truth serum and tequila',
  "{P}'s 'it's complicated' story, in one sentence",
  'The thirst trap caption {P} has drafted but never posted',
  "The first thing {P} checks out on a person ({they} thinks it's subtle)",
  'The fantasy {P} would never admit to at dinner with the in-laws',
  'The role-play scenario {P} would suggest after two glasses of wine',
  "{P}'s OnlyFans would be themed around...",
  'The pickup line that actually worked on {P}',
  "What {P}'s bedroom playlist says about {their} technique",
  "The item in {P}'s room that gets hidden when company comes over",
  "{P}'s strip club DJ intro would say...",
  'The pet name {P} uses that makes everyone else gag',
  'What {P} would do in a hotel room with no cameras and a corporate card',
  "The story behind {P}'s most regrettable hookup",
  "The filthiest thing in {P}'s camera roll",
  'The dream about a coworker {P} never talks about',
  'The morning-after text {P} has actually sent',
  'The kink {P} pretends to be shocked by',
  "What {P}'s bedsprings would testify in court",
  'The euphemism {P} uses for hooking up',
  "{P}'s love hotel alias is...",
  'The most public place {P} has considered doing it — and maybe did',
  'The naughtiest thing {P} has done at a wedding',
  'The three items {P} would grab in a sex shop with a gift card',
  'Why {P} got shushed at a sleepover',
  "The celebrity {P} would risk it all for, and exactly what 'all' includes",
  'What {P} wears to feel dangerous',
  'The flirty emoji combo {P} sends after 11pm',
  'The massage {P} books that comes with a wink',
  'The bar bathroom story {P} tells only at 2am',
  "What {P}'s neighbors have definitely overheard",
  'The costume that would make {P} lose all composure',
  "{P}'s bachelor party would get shut down for...",
  'The tan line story {P} refuses to explain',
  "The skinny-dipping story {P} pretends didn't happen",
  'The pillow talk topic {P} ruins the mood with',
  "{P}'s flirting after three shots looks like...",
  'The ex {P} would still answer the phone for at 1am, and why',
  "What {P}'s smart speaker has overheard and can never unhear",
  "The lingerie purchase {P} made 'for no reason'",
  "The fine print on {P}'s hall pass list",
  'The hot tub rule {P} has personally broken',
  "What {P} thinks 'Netflix and chill' involves, step by step",
  'The love bite explanation {P} gave that fooled absolutely no one',
  "{P}'s go-to move that {they} thinks is smooth (it is not)",
  'The compliment that instantly turns {P} to jelly',
  'The reason {P} recognizes that one motel clerk',
  'The screenshot {P} keeps for personal reasons',
  'What {P} stress-tested the new couch with',
  'The roommate rule created specifically because of {P}',
  "{P}'s dating red flag that {they} advertises as a feature",
  'The date {P} went on purely for the free food, and what it cost {them}',
  'The pregame ritual {P} does before a promising date',
  'The commandment {P} breaks most enthusiastically',
  "{P}'s adult sleepover packing list includes...",
  'The office party story that follows {P} to every job',
  'What {P} did in the back row of the movie theater',
  'The strip poker hand {P} lost on purpose',
  "{P}'s shower thoughts are actually about...",
  'The nickname {P} earned in college and paid people to forget',
  "What {P} considers 'dressed appropriately' for answering the door",
  "The scandal that would erupt if {P}'s diary went public",
  'The dare {P} regrets completing at truth or dare',
  "{P}'s ideal threesome includes which two fictional characters",
  'The last time {P} blushed and refused to say why',
]

export function buildDeck(deckId) {
  if (deckId === 'party') return [...PARTY]
  if (deckId === 'spicy') return [...SPICY]
  return [...PARTY, ...SPICY]
}
